version: "3"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modulo-vuelos-B-api
    hostname: modulo-vuelos-B-api
    ports:
      - "8019:8019"
    environment:
      DB_URL: jdbc:oracle:thin:@db:1521/XEPDB1
      DB_USERNAME: AIRLINE_ADMIN_B
      DB_PASSWORD: SITAS
      KEY_STORE_PASSWORD: 123456
