global:

  scrape_interval:     15s



scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s



    static_configs:

      - targets: ['localhost:9090']



  - job_name: 'spring-actuator'

    metrics_path: 'sitas/actuator/prometheus'

    scrape_interval: 5s

    static_configs:

      - targets: ['192.168.58.102:8080']