spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.Oracle12cDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: password
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
    driver-class-name: oracle.jdbc.driver.OracleDriver
airline-api:
  openapi:
    dev-url: http://localhost:8080/airline-api
    prod-url: https://airline-api.com

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG