server:
  port: 8080
  servlet:
    context-path: /sitas

spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

airline-api:
  dev:
    super-admin-token: ${SUPER_ADMIN_TOKEN}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USR}
    password: ${GMAIL_PWD}
    transport:
      protocol: smtp
    smtp:
      use-auth: true
      use-tls: true
  openapi:
    dev-url: https://codefact.udea.edu.co/modulo-02/
    prod-url: https://codefact.udea.edu.co/modulo-02/

logging:
  level:
    root: debug
    "[org.springframework]": debug
