server:
  port: 8080
  servlet:
    context-path: /sitas

spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  
airline-api:
  openapi:
    dev-url: http://localhost:8080/sitas
    prod-url: https://airline-api.com

logging:
  level:
    root: debug
    org.springframework: debug