ALTER SESSION
SET
  CONTAINER = XEPDB1;

ALTER SESSION
SET
  "_ORACLE_SCRIPT" = true;

CREATE USER "SEATDB_PROD" IDENTIFIED BY "SEATDB_PROD" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

ALTER USER "SEATDB_PROD" QUOTA UNLIMITED ON "USERS";

GRANT CREATE SESSION TO "SEATDB_PROD";

GRANT "RESOURCE" TO "SEATDB_PROD";

ALTER USER "SEATDB_PROD" DEFAULT ROLE "RESOURCE";